FROM alpine:3

LABEL author="Gilbert Hutapea"
LABEL company="Solusi Migrasi Teknologi" website="https://somitek.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"